(PUP-2889) Rescue LoadError when wevtapi.dll is not present
 - Vendoring patch for https://github.com/djberg96/win32-eventlog/pull/10/

The newer event logging APIs are not available prior to 2008 and Vista. As
a result, the following would fail on 2003:

    C:\> ruby -e "require 'win32/eventlog'"
    LoadError: can't convert Symbol into String.
    Could not open library 'wevtapi.dll': The specified module could not be found.

This commit rescues the LoadError so that the gem can continue to be loaded on
older systems.